import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { scanTree } from "./check-no-secrets.mjs";

const appId = `cli_${"0123456789abcdef"}`;
const hex32 = "ab".repeat(16);
const openId = `ou_${"a".repeat(20)}`;
const docToken = "d".repeat(27);
const liveHost = `https://${"not-example"}.workers.dev`;
const placeholderHost = "https://example.workers.dev";

async function withTree(files, fn) {
  const root = await mkdtemp(join(tmpdir(), "scan-"));
  try {
    for (const [rel, text] of Object.entries(files)) {
      const path = join(root, rel);
      await mkdir(join(path, ".."), { recursive: true });
      await writeFile(path, text);
    }
    await fn(root);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

test("flags a Feishu app id", async () => {
  await withTree({ "src/app.ts": `const id = "${appId}";` }, async (root) => {
    const failures = scanTree(root);
    assert.equal(failures.length, 1);
    assert.match(failures[0], /app id/);
  });
});

test("flags account_id and a KV id in wrangler config", async () => {
  await withTree(
    {
      "wrangler.jsonc": `{\n  "account_id": "${hex32}",\n  "kv_namespaces": [{ "binding": "OAUTH_KV", "id": "${hex32}" }]\n}\n`,
    },
    async (root) => {
      const failures = scanTree(root);
      assert.ok(failures.some((line) => /account_id/.test(line)));
      assert.ok(failures.some((line) => /KV id/.test(line)));
    },
  );
});

test("flags a 32-hex id outside wrangler config", async () => {
  await withTree({ "notes.txt": `id ${hex32}\n` }, async (root) => {
    const failures = scanTree(root);
    assert.equal(failures.length, 1);
    assert.match(failures[0], /32-hex/);
  });
});

test("flags the 64-hex secret the wizard generates", async () => {
  const hex64 = "ab".repeat(32);
  await withTree({ "notes.txt": `COOKIE_SECRET=${hex64}\n` }, async (root) => {
    const failures = scanTree(root);
    assert.equal(failures.length, 1);
    assert.match(failures[0], /64-hex/);
  });
  await withTree({ "notes.txt": `secret ${"CD".repeat(32)}\n` }, async (root) => {
    const failures = scanTree(root);
    assert.equal(failures.length, 1);
    assert.match(failures[0], /64-hex/);
  });
});

test("ignores 64-hex samples only inside generated wrangler types", async () => {
  const hex64 = "ab".repeat(32);
  const banner = `// Generated by Wrangler by running \`wrangler types\` (hash: ${hex32})\n`;
  await withTree({ "worker-configuration.d.ts": `${banner} * @example "${hex64}"\n` }, async (root) => {
    assert.deepEqual(scanTree(root), []);
  });
  await withTree({ "worker-configuration.d.ts": `${banner}const secret = "${hex64}";\n` }, async (root) => {
    const failures = scanTree(root);
    assert.equal(failures.length, 1);
    assert.match(failures[0], /64-hex/);
  });
  await withTree({ "src/app.ts": `/** @example "${hex64}" */\n` }, async (root) => {
    const failures = scanTree(root);
    assert.equal(failures.length, 1);
    assert.match(failures[0], /64-hex/);
  });
});

test("ignores only the wrangler types banner hash", async () => {
  const banner = `// Generated by Wrangler by running \`wrangler types\` (hash: ${hex32})\n`;
  const flagged = `// Generated by Wrangler by running \`wrangler types --strict-vars=false\` (hash: ${hex32})\n`;
  await withTree({ "worker-configuration.d.ts": banner }, async (root) => {
    assert.deepEqual(scanTree(root), []);
  });
  await withTree({ "worker-configuration.d.ts": flagged }, async (root) => {
    assert.deepEqual(scanTree(root), []);
  });
  await withTree(
    { "worker-configuration.d.ts": `${banner}const id = "${hex32}";\n` },
    async (root) => {
      const failures = scanTree(root);
      assert.equal(failures.length, 1);
      assert.match(failures[0], /32-hex/);
    },
  );
});

test("flags a non-placeholder workers.dev host and allows the placeholder", async () => {
  await withTree({ "src/live.ts": `const url = "${liveHost}";\n` }, async (root) => {
    const failures = scanTree(root);
    assert.equal(failures.length, 1);
    assert.match(failures[0], /workers\.dev/);
  });
  await withTree({ "src/ok.ts": `const url = "${placeholderHost}";\n` }, async (root) => {
    assert.deepEqual(scanTree(root), []);
  });
});

test("flags a long open_id and allows short placeholders", async () => {
  await withTree({ "src/id.ts": `const id = "${openId}";\n` }, async (root) => {
    const failures = scanTree(root);
    assert.equal(failures.length, 1);
    assert.match(failures[0], /open_id/);
  });
  await withTree({ "src/id.ts": `const id = "ou_owner";\n` }, async (root) => {
    assert.deepEqual(scanTree(root), []);
  });
});

test("flags a 27-character doc token in fixtures only", async () => {
  await withTree({ "test/fixtures/pages.json": `{ "doc_id": "${docToken}" }\n` }, async (root) => {
    const failures = scanTree(root);
    assert.equal(failures.length, 1);
    assert.match(failures[0], /doc token/);
  });
  await withTree({ "src/sample.ts": `const doc = "${docToken}";\n` }, async (root) => {
    assert.deepEqual(scanTree(root), []);
  });
  await withTree({ "test/fixtures/pages.json": `{ "doc_id": "doxcnEmoji" }\n` }, async (root) => {
    assert.deepEqual(scanTree(root), []);
  });
});

test("flags secret names declared as wrangler vars", async () => {
  await withTree(
    { "wrangler.jsonc": `{\n  "vars": { "FEISHU_APP_SECRET": "" }\n}\n` },
    async (root) => {
      const failures = scanTree(root);
      assert.equal(failures.length, 1);
      assert.match(failures[0], /FEISHU_APP_SECRET/);
    },
  );
});

test("applies path rules when the scan root has a trailing slash", async () => {
  await withTree(
    {
      "wrangler.jsonc": `{\n  "vars": { "FEISHU_APP_SECRET": "" }\n}\n`,
      "test/fixtures/pages.json": `{ "doc_id": "${docToken}" }\n`,
    },
    async (root) => {
      const failures = scanTree(`${root}/`);
      assert.ok(failures.some((line) => line.startsWith("wrangler.jsonc") && /FEISHU_APP_SECRET/.test(line)));
      assert.ok(failures.some((line) => line.startsWith("test/fixtures/pages.json") && /doc token/.test(line)));
    },
  );
});

test("accepts a de-personalized tree", async () => {
  await withTree(
    {
      "wrangler.jsonc": `{\n  "name": "lark-general-connector",\n  "vars": { "PUBLIC_URL": "${placeholderHost}" },\n  "kv_namespaces": [{ "binding": "OAUTH_KV" }]\n}\n`,
      "src/server.ts": `const name = "lark-general-connector";\n`,
      "test/fixtures/pages.json": `{ "doc_id": "doxcnEmoji", "title": "Star Harbor Guide" }\n`,
    },
    async (root) => {
      assert.deepEqual(scanTree(root), []);
    },
  );
});
